---
sudo: false
language: ruby
matrix:
  include:
    - rvm: "1.9.3-p545"
      env: COMMAND=rake
    - rvm: "2.2.4"
      env: COMMAND=rspec
install: bundle install --deployment --without debug
script: bundle exec $COMMAND
